FIX: update travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,3 +1,4 @@
+# DANTsR Build
 language: r
 sudo: false
 cache:
@@ -12,119 +13,99 @@ allow_failures:
 
 latex: false
 compiler: clang
-# osx_image: xcode9
+osx_image: xcode9
 
 env:
   global:
   - R_BUILD_ARGS=" --no-build-vignettes --no-manual "
-  - R_CHECK_ARGS=" --timings --as-cran --no-manual"
+  - R_CHECK_ARGS=" --timings --as-cran --no-manual --install-args=--build"
   - R_CHECK_TIME="TRUE"
   - R_CHECK_TESTS="TRUE"
   - _R_CHECK_TIMINGS_="0"
   - _R_CHECK_FORCE_SUGGESTS_="0"
+  - DISPLAY=:99.0
   - BOOTSTRAP_LATEX=1
 
 before_install:
-  - export CCACHE=ccache
+  - ulimit -n 2048
+  - wget -O travis_helpers.sh http://bit.ly/travis_helpers
+  - source travis_helpers.sh
+  - rm travis_helpers.sh
+  - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
   - export PROJ_DIR=`basename ${TRAVIS_BUILD_DIR}`
   - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
-  - fname=travis_helpers.sh
-  - wget -O ${fname} http://bit.ly/travis_helpers
-  - cat ${fname}; source ${fname}; rm ${fname}
+  - wget -O travis_helpers.sh http://bit.ly/travis_helpers
+  - source travis_helpers.sh
+  - rm travis_helpers.sh
+  - export rver=`r_version`;
+  - cat DESCRIPTION
+  - export PACKAGE_NAME=`package_name`
+  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
   # does all the clang exports
   - x=`export_clang_cxx`; eval ${x}
+  - if [ "$TRAVIS_OS_NAME" = "osx" ];
+    then
+      no_open_mp ;
+    fi
   - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
   - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
   - clang_cxx
-  - cat ~/.R/Makevars
+  - hdf5_install ;
   - export cmake_version="3.11"
   - cmake --version
   - x=`cmake_setup`; echo "${x}"; eval ${x};
   - cmake --version
   - ./cleanup
-  - export PACKAGE_NAME=`package_name`
-  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
-  - gh_binary_install stnava/ITKR
-  - export ants_user=ANTsX
-  - gh_binary_install ${ants_user}/ANTsRCore ${ants_user}/ANTsR
-  - echo "Done Binary Installs"
-  - cat DESCRIPTION
-  - install_remotes_no_dep
-  - cat DESCRIPTION
-  - echo $PATH ;
-  - if [ "$TRAVIS_OS_NAME" == "osx" ];
-    then
-      no_open_mp ;
-      brew install ccache;
-      export PATH="/usr/local/opt/ccache/libexec:$PATH";
-    fi
-  - travis_run_cache
-
-before_script:
-  - cat ~/.R/Makevars
-  # - source ~/.R/Makevars
-  - x=`export_clang_cxx`; eval ${x}
+  - Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type = 'source', repos=c(CRAN='https://cran.rstudio.com'))"
+  - Rscript -e "install.packages( c('magrittr','knitr','rmarkdown','testthat'), repos=c(CRAN='https://cran.rstudio.com'))"
+  - Rscript -e 'install.packages("rsvd")'
+  - Rscript -e 'install.packages("magic")'
+  - Rscript -e 'install.packages("ggplot2")'
+  - Rscript -e 'install.packages("psych")'
+  - Rscript -e 'install.packages("randomForest")'
   - cd ..
+  - git clone https://github.com/muschellij2/ghtravis.git
+  - R CMD INSTALL ghtravis
+  - cd ANTsR
+  - gh_binary_install  stnava/ITKR ANTsX/ANTsRCore ANTsX/ANTsR
+  - export ants_user=ANTsX
+  - echo "Done Binary Installs"
+
+install:
+  - echo "skip this"
 
 script:
-  - travis_wait 100 R CMD build ${PROJ_DIR} ${R_BUILD_ARGS}
+  - x=`export_clang_cxx`; eval ${x}
+  - travis_wait 100 R CMD build ${R_BUILD_ARGS} .
   - rm -f travis_wait*.log
-  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
-  - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_FILE_NAME}";
+  - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
+  - ls
+  - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
   - rm -f travis_wait*.log
-  - check_fail
-  - check_warnings
+  - if [[ $CHECK_RET -ne 0 ]];
+    then
+      echo "R CMD check failed";
+      check_fail;
+      dump_logs;
+      check_warnings ;
+      travis_terminate 1;
+    fi
 
-jobs:
-  include:
-    - name: "linux"
-      os: linux
-    - name: "OSX"
-      os: osx
-    - stage: "Deployment"
-      if: tag IS present
-      script:
-        - travis_wait 100 R CMD INSTALL --debug --build ${PROJ_DIR};
-      deploy:
-        provider: releases
-        api_key:
-          secure: VevZHK5WDwd2mFSrF3+b2jTRzImb6juOgewcOvZ8LJ2S70khn64Kx4+JGUvk5miKWVbKnHIhPxOJY50muO9sT15ApP+HFZYpiVpx4l/hEypk9zmJD+f+ERuN7j8elCzUZqet3v77XD+pBcYMxFARew4gGDkG2LO5casij0YNiyQ=
-        file_glob: true
-        file: ${PROJ_DIR}*.t*gz
-        skip_cleanup: true
-        overwrite: true
-        on:
-          repo: jeffduda/${PROJ_DIR}
-          tags: true
-          all_branches: true
-      os: linux
-    - stage: "Deployment"
-      if: tag IS present
-      script:
-        - travis_wait 100 R CMD INSTALL --debug --build ${PROJ_DIR};
-      deploy:
-        provider: releases
-        api_key:
-          secure: VevZHK5WDwd2mFSrF3+b2jTRzImb6juOgewcOvZ8LJ2S70khn64Kx4+JGUvk5miKWVbKnHIhPxOJY50muO9sT15ApP+HFZYpiVpx4l/hEypk9zmJD+f+ERuN7j8elCzUZqet3v77XD+pBcYMxFARew4gGDkG2LO5casij0YNiyQ=
-        file_glob: true
-        file: ${PROJ_DIR}*.t*gz
-        skip_cleanup: true
-        overwrite: true
-        on:
-          repo: jeffduda/${PROJ_DIR}
-          tags: true
-          all_branches: true
-      os: osx
 
 after_failure:
-  - cat ${PACKAGE_NAME}.Rcheck/00install.out
-  - cat ${PACKAGE_NAME}.Rcheck/00check.log
-  - cat ${PACKAGE_NAME}.Rcheck/00_pkg_src/${PACKAGE_NAME}/src/Makevars
-
+  - dump_logs
 
 after_success:
-  - cat ${PACKAGE_NAME}.Rcheck/00install.out
-  - cat ${PACKAGE_NAME}.Rcheck/00check.log
+  - dump_logs
+  - ls
+  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1);
+  - PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'` ;
+  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
+      PKG_FILE_NAME=$(ls -1t *.tgz | head -n  1);
+      PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tgz/_'"R${rver}"'.tgz/'` ;
+    fi
+  - mv ${PKG_FILE_NAME} ${PKG_TARBALL_WITH_R} ;
+  - PKG_FILE_NAME=${PKG_TARBALL_WITH_R}
 
 notifications:
   email:
@@ -132,3 +113,21 @@ notifications:
     - jeff.duda@gmail.com
     on_success: change
     on_failure: always
+
+# so no overwrite of linux build
+before_deploy:
+  - if [ "$TRAVIS_OS_NAME" = "osx" ];
+    then
+      rm -f *.tar.gz;
+    fi
+
+deploy:
+  provider: releases
+  api_key:
+    secure: VevZHK5WDwd2mFSrF3+b2jTRzImb6juOgewcOvZ8LJ2S70khn64Kx4+JGUvk5miKWVbKnHIhPxOJY50muO9sT15ApP+HFZYpiVpx4l/hEypk9zmJD+f+ERuN7j8elCzUZqet3v77XD+pBcYMxFARew4gGDkG2LO5casij0YNiyQ=
+  file: ${PKG_FILE_NAME}
+  skip_cleanup: true
+  on:
+    tags: true
+    repo: jeffduda/${PROJ_DIR}
+    all_branches: true
